config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new # Guest user (not logged in)
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]

    # User can destroy their own posts and comments
    can :destroy, Post, author: user.id
    can :destroy, Comment, user: user.id

    # Admins can delete any post or comment
    can :destroy, Post, author: user.id, role: 'admin'
    can :destroy, Comment, user: user.id, role: 'admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_post_comments_counter

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :increment_likes_counter

  def increment_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter
  after_create :recent_comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def set_default_posts_counter
    self.posts_counter ||= 0
  end
  def set_defaults
    self.likes_counter ||= 0
    self.comments_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[email password password_confirmation name posts_counter])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = @user
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment created!'
    else
      flash.now[:errors] = 'Invalid comment!'
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    post = @comment.post
    user = post.author
    @comment.destroy
    redirect_to user_post_path(user, post), notice: 'Comment was successfully deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(user_id: @user.id, post_id: @post.id)
    return unless @like.save

    redirect_to user_post_path(@user.id, @post)
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except:
  %i[index show]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
    @posts = @posts.paginate(page: params[:page], per_page: 3)
  end

  def show
     @post = Post.includes(:author).find(params[:id])

    if @post
      @user = @post.author
      @comments = @post.comments
    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(params[:user_id])
    end
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post sucessfully created!'
    else
      puts @user
      puts @post.errors.full_messages
      flash.now[:errors] = 'No post!'
      render :new
    end
  end
  
  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      @recent_posts = @user.most_recent_posts
    else
      flash[:alert] = 'User not found'
      redirect_to root_path
    end
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<h1>Comments for <%= @post.title %></h1>

<% @comments.each do |comment| %>
  <div class="comment">
    <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
     <% if can?(:destroy, comment) %>
     <%= button_to 'Delete Comment', user_post_comment_path(@user, post, comment), method: :delete, class: "delete-btn" %>
    <% end %>
  </div>
<% end %> 3.

app/views/comments/new.html.erb
<div class="comment-container">
<h3>Add a new Comment</h3>
<div class="comment-form">
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path do |form| %>
<div>
<%= form.label :text, required: true%>
<%= form.text_field :text, required: true %>
</div>
<%= form.submit "Submit" %>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if flash[:notice].present? %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div>
    <%= flash[:alert] %>
  </div>
<% end %>


  <div>
  <% if user_signed_in? %>
  <%= link_to "Profile", edit_user_registration_path %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% end %>
  </div>


    <%= yield %>
  </body>
</html>

app/views/likes/like.html.erb
<% stylesheet_link_tag('index')%>
<div class="likes-container">
<button class="Add-likes">Like comment/post</button>
<div class="comment-form">
</div>
</div>

app/views/posts/index.html.erb
<div class="posts-container">
<div class="users">
<%= render 'shared/user', user:@user %>
</div>

<div class="posts">
<h2>All Posts</h2>

<%=link_to "Add post", new_user_post_path(@user)%>

<% @posts.each do |post| %>
<%= render 'shared/post', post: post, user:@user %>

<div class="post-content">
<%= link_to "Add Comment", new_user_post_comment_path(@user, post) %>

<%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>

<%= form.submit 'Like' %>
<% end %>
<% if can?(:destroy, @post) %>
<%= button_to 'Delete Post', user_post_path(@user, post), method: :delete, class: 'delete-btn' %>
<% end %>

</div>

<% if post.recent_comments.present? %>
<% comments = post.recent_comments %>
<%= render "shared/comments", comments:comments %>
<% end %>
<% end %>
</div>
</div>

<%= link_to 'Pagination', user_posts_path(@user), class: 'pagination see-all-posts-btn' %>

app/views/posts/new.html.erb
<div class= "post-form">
  <h2 class= "create-post">Create a post</h2>

  <%# <%= form_with model: @post, url: user_posts_path(@user) do |f| %> 
  <%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |f| %>
    <div class= "title-input">
      <%= f.label :title %>
      <%= f.text_field :title, required: true %>
    </div>

    <div class= "comment-input">
      <%= f.label :text %>
      <%= f.text_field :text, required: true %>
    </div>
<!-- Add fields for likes_counter and comments_counter -->
    <div class="likes-counter-input">
      <%= f.label :likes_counter %>
      <%= f.number_field :likes_counter, value: 0, min: 0 %>
    </div>

    <div class="comments-counter-input">
      <%= f.label :comments_counter %>
      <%= f.number_field :comments_counter, value: 0, min: 0 %>
    </div>
    
    <div class= "submit">
      <%= f.submit "Submit" %>
    </div>
    <% if @post.errors.any? %>
  <div class="error-messages">
    <h2>Errors:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
         <% end %>
    </ul>
  </div>
  <% end %>
 <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-show">
<div class="post-show">

<div class="post-title-show">
<h1><%= @post.title %></h1>

<div class="post-interact">
<p>comments: <%= @post.comments_counter %></p>
<p>likes: <%= @post.likes_counter %></p>
</div>
</div>

<div>
<p><%= @post.text %></p>
</div>

</div>

<div class="">
<h2>Comments</h2>
<%= render "shared/comments", comments:@comments %>
</div>

</div>

app/views/shared/_comments.html.erb
<div class="comments">
  <%  comments.each.each do |comment| %>
    <div class="comment">
      <p><%= comment.user.name%> :<%= comment.text %></p>
    </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="post">
<%=link_to user_post_path(user, post) do %>
<div class="single-post-cont">
<div class="post-title">
<h1><%= post.title %></h1>
</div>
<div class="post-content">
<p><%= post.text %></p>
</div>
<div class="interactions">
<p>comments: <%= post.comments_counter %></p>
<p>likes: <%= post.likes_counter %></p>
</div>
</div>
<% end %>
</div>

app/views/shared/_user.html.erb
<div class="users-container">
<%=link_to user_path(user) do %>
<div class="container-components">
<div class="img-container">
<img src="<%= user.photo_link %>"
alt="<%= user.name %>" />
</div>
<div class="userpost-container">
<h1 class="user-name"><%= user.name %></h1>
<p class="user-post">Number of posts: <%= user.posts_counter %></p>
</div>
</div>
<% end %>

</div>

app/views/users/index.html.erb
<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="show-page">
<div class="users">
<%= render 'shared/user', user:@user %>
</div>
<div class="posts">
<h2>Recent Posts</h2>
<% @recent_posts.each do |post|
 %>
<%= render 'shared/post', post:post, user:@user %>
<% end %>
</div>
<%=link_to 'See all posts', user_posts_path(@user) %>
</div>